CLIENT_ID="354e1512-776d-47b9-9278-3dc4c5e62e66"
CLIENT_SECRET="uau8Q~~B3DnYJcNiFyB2DeaOGxkdt~al6Vqihcmt"
TENANT_ID="787beb16-0600-4e9e-b636-9993f8d4b23a"
SHAREPOINT_HOST="kenaiusa.sharepoint.com"
SITE_NAME="Oracle ConvoPilot"
DOC_LIB_PATH="SharePoint/Docs1"
RUN_ENV="cloud"